export const joinSlots = [
  // mon
  [
    { id: 0, numSlots: 0, selected: false },
    { id: 1, numSlots: 1, selected: false },
    { id: 2, numSlots: 0, selected: false },
    { id: 3, numSlots: 3, selected: false },
    { id: 4, numSlots: 2, selected: false },
    { id: 5, numSlots: 9, selected: false },
    { id: 6, numSlots: 5, selected: false },
    { id: 7, numSlots: 5, selected: false },
    { id: 8, numSlots: 7, selected: false },
    { id: 9, numSlots: 1, selected: false },
    { id: 10, numSlots: 3, selected: false },
    { id: 11, numSlots: 8, selected: false },
  ],
  // tue
  [
    { id: 0, numSlots: 0, selected: false },
    { id: 1, numSlots: 1, selected: false },
    { id: 2, numSlots: 0, selected: false },
    { id: 3, numSlots: 3, selected: false },
    { id: 4, numSlots: 2, selected: false },
    { id: 5, numSlots: 9, selected: false },
    { id: 6, numSlots: 5, selected: false },
    { id: 7, numSlots: 5, selected: false },
    { id: 8, numSlots: 7, selected: false },
    { id: 9, numSlots: 1, selected: false },
    { id: 10, numSlots: 3, selected: false },
    { id: 11, numSlots: 8, selected: false },
  ],
  // wed
  [
    { id: 0, numSlots: 0, selected: false },
    { id: 1, numSlots: 1, selected: false },
    { id: 2, numSlots: 0, selected: false },
    { id: 3, numSlots: 3, selected: false },
    { id: 4, numSlots: 2, selected: false },
    { id: 5, numSlots: 9, selected: false },
    { id: 6, numSlots: 5, selected: false },
    { id: 7, numSlots: 5, selected: false },
    { id: 8, numSlots: 7, selected: false },
    { id: 9, numSlots: 1, selected: false },
    { id: 10, numSlots: 3, selected: false },
    { id: 11, numSlots: 8, selected: false },
  ],
  // thu
  [
    { id: 0, numSlots: 0, selected: false },
    { id: 1, numSlots: 1, selected: false },
    { id: 2, numSlots: 0, selected: false },
    { id: 3, numSlots: 3, selected: false },
    { id: 4, numSlots: 2, selected: false },
    { id: 5, numSlots: 9, selected: false },
    { id: 6, numSlots: 5, selected: false },
    { id: 7, numSlots: 5, selected: false },
    { id: 8, numSlots: 7, selected: false },
    { id: 9, numSlots: 1, selected: false },
    { id: 10, numSlots: 3, selected: false },
    { id: 11, numSlots: 8, selected: false },
  ],
  // fri
  [
    { id: 0, numSlots: 0, selected: false },
    { id: 1, numSlots: 1, selected: false },
    { id: 2, numSlots: 0, selected: false },
    { id: 3, numSlots: 3, selected: false },
    { id: 4, numSlots: 2, selected: false },
    { id: 5, numSlots: 9, selected: false },
    { id: 6, numSlots: 5, selected: false },
    { id: 7, numSlots: 5, selected: false },
    { id: 8, numSlots: 7, selected: false },
    { id: 9, numSlots: 1, selected: false },
    { id: 10, numSlots: 3, selected: false },
    { id: 11, numSlots: 8, selected: false },
  ],
  // sat
  [
    { id: 0, numSlots: 0, selected: false },
    { id: 1, numSlots: 1, selected: false },
    { id: 2, numSlots: 0, selected: false },
    { id: 3, numSlots: 3, selected: false },
    { id: 4, numSlots: 2, selected: false },
    { id: 5, numSlots: 9, selected: false },
    { id: 6, numSlots: 5, selected: false },
    { id: 7, numSlots: 5, selected: false },
    { id: 8, numSlots: 7, selected: false },
    { id: 9, numSlots: 1, selected: false },
    { id: 10, numSlots: 3, selected: false },
    { id: 11, numSlots: 8, selected: false },
  ],
  // sun
  [
    { id: 0, numSlots: 0, selected: false },
    { id: 1, numSlots: 1, selected: false },
    { id: 2, numSlots: 0, selected: false },
    { id: 3, numSlots: 3, selected: false },
    { id: 4, numSlots: 2, selected: false },
    { id: 5, numSlots: 9, selected: false },
    { id: 6, numSlots: 5, selected: false },
    { id: 7, numSlots: 5, selected: false },
    { id: 8, numSlots: 7, selected: false },
    { id: 9, numSlots: 1, selected: false },
    { id: 10, numSlots: 3, selected: false },
    { id: 11, numSlots: 8, selected: false },
  ],
];
